// ADD RECIPES SITE LINK LATER
const recipesData = [
    {"title": "Creamy Shrimp Pasta", "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit.", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Pastas", "Dinner", "Delicious"], "image": "Resources/Images/Recipes/Shrimp-and-Scallop-Pasta-in-Garlic-Cream-Sauce.jpg"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "First List"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "First List"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "First List"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Luxorious Cake", "description": "This is a featured recipe", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4.8, "tags": ["Food", "Delicious", "Dessert", "Featured"], "image": "Resources/Images/Recipes/Chocolate-Raspberry-Icebox-Cake.jpg"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4.2, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4.5, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
    {"title": "Recipe Title", "description": "Recipe description", "publisher": "CKINTS", "date-published": "Feb 19, 2024", "rating": 4, "tags": ["Food", "Delicious", "Dessert"], "image": "Resources/Images/Recipes/Pecan-Crusted-Salmon.png"},
];
